=== nzzdev/Q-election-votes/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Parlamentswahlen",
  "properties": {
    "title": {
      "title": "Titel",
      "type": "string"
    },
    "subtitle": {
      "title": "Untertitel",
      "type": "string"
    },
    "threshold": {
      "title": "% Hürde",
      "description": "Falls eine % Hürde exisitert, bitte Prozentzahl eintragen",
      "type": "number"
    },
    "parties": {
      "title": "Parteien",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "title": "Parteiname",
            "type": "string"
          },
          "abbreviation": {
            "title": "Kürzel",
            "type": "string"
          },
          "color": {
            "title": "Farbe",
            "type": "object",
            "properties": {
              "colorCode": {
                "title": "Farbcode",
                "type": "string"
              },
              "classAttribute": {
                "title": "CSS Klassename",
                "type": "string"
              }
            }
          },
          "percentage": {
            "title": "Stimmen in %",
            "type": "number"
          },
          "previous": {
            "title": "Stimmen letzte Wahl in %",
            "type": "number"
          }
        }
      }
    },
    "notes": {
      "title": "Bemerkungen",
      "type": "string"
    },
    "sources": {
      "title": "Quellen",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "text": {
            "title": "Text",
            "type": "string"
          },
          "link": {
            "Q:type": "link",
            "title": "Link",
            "type": "object",
            "properties": {
              "url": {
                "title": "Url",
                "type": "string"
              },
              "isValid": {
                "type": "boolean"
              }    
            }
          }
        }
      }
    }
  },
  "required": [
    "title"
  ]
}

=== nzzdev/Q-election-votes/resources/fixtures/data/before-v2.0.0/results-partly-empty-party-names.json
{
  "title": "FIXTURE: results - partly previous - color classes",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes": "Jemand musste Josef's K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines Morgens verhaftet.",
  "parties": [
    {
      "color": {
        "classAttribute": "s-viz-color-party-svp-5"
      },
      "name": "",
      "previous": 41.5,
      "percentage": 40
    },
    {
      "color": {
        "classAttribute": "s-viz-color-party-fdp-5"
      },
      "percentage": 4
    },
    {
      "color": {
        "classAttribute": "s-viz-color-party-glp-5"
      },
      "name": "GLP",
      "previous": 0,
      "percentage": 1
    },
    {
      "color": {
        "classAttribute": "s-viz-color-party-sp-5"
      },
      "name": "SP",
      "percentage": 12
    },
    {
      "color": {
        "classAttribute": "s-viz-color-party-gps-5"
      },
      "name": "Grüne",
      "previous": 8.4,
      "percentage": 16
    },
    {
      "color": {
        "classAttribute": "s-viz-color-party-default-5"
      },
      "name": "andere",
      "percentage": 6
    }
  ]
}

=== nzzdev/Q-election-votes/resources/fixtures/data/no-results-threshold-others.json
{
  "title": "FIXTURE: no results - threshold - others",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes": "Jemand musste Josef's K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines Morgens verhaftet.",
  "threshold": 5,
  "parties": [
    {
      "color": {
        "colorCode": "#0a0a0a"
      },
      "name": "Union",
      "previous": 41.5
    },
    {
      "color": {
        "colorCode": "#d1cc00"
      },
      "name": "FDP",
      "previous": 4.8
    },
    {
      "color": {
        "colorCode": "#0084c7"
      },
      "name": "AfD",
      "previous": 0
    },
    {
      "color": {
        "colorCode": "#8440a3"
      },
      "name": "Die Linke",
      "previous": 8.6
    },
    {
      "color": {
        "colorCode": "#66a622"
      },
      "name": "Grüne ",
      "previous": 8.4
    },
    {
      "color": {
        "colorCode": "#616161"
      },
      "name": "andere",
      "previous": 6.3
    }
  ]
}

=== nzzdev/Q-election-votes/resources/fixtures/data/results-long-names-threshold-others-color-codes.json
{
  "title": "FIXTURE: results - long names - threshold - others - color codes",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Möglichkeit zusätzliche Informationen als Untertitel zu erfassen",
  "notes": "Jemand musste Josef's K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines Morgens verhaftet.",
  "threshold": 0.67,
  "parties": [
    {
      "name": "Socialistische Partij",
      "color": {
        "colorCode": "#8440a3"
      },
      "previous": 9.6,
      "percentage": 9.2
    },
    {
      "name": "Partij van de Arbeid",
      "color": {
        "colorCode": "#c31906"
      },
      "previous": 24.8,
      "percentage": 5.7
    },
    {
      "name": "GroenLinks",
      "color": {
        "colorCode": "#66a622"
      },
      "previous": 2.3,
      "percentage": 8.9
    },
    {
      "name": "Democraten 66",
      "color": {
        "colorCode": "#22a682"
      },
      "previous": 8,
      "percentage": 12
    },
    {
      "name": "ChristenUnie",
      "color": {
        "colorCode": "#0084c7"
      },
      "previous": 3.1,
      "percentage": 3.4
    },
    {
      "name": "Christen-Democratisch Appèl",
      "color": {
        "colorCode": "#01b1c0"
      },
      "previous": 8.5,
      "percentage": 12.5
    },
    {
      "name": "Volkspartij voor Vrijheid en Democratie",
      "color": {
        "colorCode": "#d28b00"
      },
      "previous": 26.5,
      "percentage": 21.3
    },
    {
      "name": "Partij voor de Vrijheid",
      "color": {
        "colorCode": "#0a0a0a"
      },
      "previous": 10.1,
      "percentage": 13.1
    },
    {
      "name": "andere",
      "color": {
        "colorCode": "#616161"
      },
      "previous": 6.7,
      "percentage": 13.6
    }
  ]
}

=== nzzdev/Q-election-votes/resources/fixtures/data/results-threshold-color-codes-overwrite.json
{
  "title": "FIXTURE: results - threshold - classes overwrite color",
  "sources": [
    {
      "text": "NZZ",
      "link": {
        "url": "https://nzz.ch",
        "isValid": true
      }
    }
  ],
  "subtitle": "Color codes contain party color, class attribute is set to default party color, so every bar should have the same default color",
  "notes": "Jemand musste Josef's K. verleumdet haben, denn ohne dass er etwas Böses getan hätte, wurde er eines Morgens verhaftet.",
  "threshold": 5,
  "parties": [
    {
      "color": {
        "colorCode": "#01b1c0",
        "classAttribute": "s-viz-color-party-default-5"
      },
      "name": "SVP",
      "previous": 41.5,
      "percentage": 40
    },
    {
      "color": {
        "colorCode": "#0084c7",
        "classAttribute": "s-viz-color-party-default-5"
      },
      "name": "FDP",
      "percentage": 4
    },
    {
      "color": {
        "colorCode": "#22a682",
        "classAttribute": "s-viz-color-party-default-5"
      },
      "name": "GLP",
      "previous": 0,
      "percentage": 1
    },
    {
      "color": {
        "colorCode": "#c31906",
        "classAttribute": "s-viz-color-party-default-5"
      },
      "name": "SP",
      "percentage": 12
    },
    {
      "color": {
        "colorCode": "#66a622",
        "classAttribute": "s-viz-color-party-default-5"
      },
      "name": "Grüne",
      "previous": 8.4,
      "percentage": 16
    },
    {
      "color": {
        "colorCode": "#000",
        "classAttribute": "s-viz-color-party-default-5"
      },
      "name": "andere",
      "percentage": 6
    }
  ]
}
